#!/bin/sh
while read file
do
    case "$1" in
        "C-r")
            convert -rotate 90 "$file" "$file" ;;
		"r")
			convert -rotate -90 "$file" "$file" ;;
        "C-c")
            echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
            feh --bg-scale "$file" ;;
    esac
done
