(deftheme graphite
  "Created 2020-04-11.")

(custom-theme-set-faces
 'graphite
 '(cursor ((t (:background "#0b2d63"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#d26937"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#1f388a"))))
 '(highlight ((t (:background "#0a0422"))))
 '(region ((t (:background "#0a0422"))))
 '(shadow ((t (:foreground "#242337"))))
 '(secondary-selection ((t (:background "#095b85"))))
 '(trailing-whitespace ((t (:background "#c23127"))))
 '(font-lock-builtin-face ((t (:foreground "#3b48e3"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#182038"))))
 '(font-lock-comment-face ((t (:foreground "#182038"))))
 '(font-lock-constant-face ((t (:foreground "#5EB0B1" :weight bold))))
 '(font-lock-doc-face ((t (:foreground "#0b2d63"))))
 '(font-lock-function-name-face ((t (:foreground "#3ea290"))))
 '(font-lock-keyword-face ((t (:foreground "#1f388a" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#12111f"))))
 '(font-lock-preprocessor-face ((t (:foreground "#12111f"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#edb443"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#edb443"))))
 '(font-lock-string-face ((t (:foreground "royal blue"))))
 '(font-lock-type-face ((t (:foreground "#1e1212"))))
 '(font-lock-variable-name-face ((t (:foreground "#095b85"))))
 '(font-lock-warning-face ((t (:foreground "#12111f"))))
 '(button ((t (:foreground "#1f388a" :box 1))))
 '(link ((t (:foreground "#3b48e3" :underline t))))
 '(link-visited ((t (:foreground "#edb443"))))
 '(fringe ((t (:background "#11151c" :foreground "white"))))
 '(header-line ((t (:background "#222222" :foreground "#1f388a"))))
 '(tooltip ((t (:background "#0c1014" :foreground "white"))))
 '(mode-line ((t (:background "#080808" :foreground "#1f388a" :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:foreground "#142763"))))
 '(mode-line-inactive ((t (:background "#080808" :foreground "#182038" :box nil))))
 '(isearch ((t (:inverse-video t))))
 '(isearch-fail ((t (:foreground "#05070f"))))
 '(lazy-highlight ((t (:foreground "#091f2e" :background "#edb443"))))
 '(match ((t (:background "#1e1212"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(menu ((((type tty)) (:inverse-video t)) (((type x-toolkit)) nil) (t (:inverse-video t))))
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "#242337" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "SRC" :family "Hack")))))

(provide-theme 'graphite)
